### ISSUE TITLE
CIA description's for use with Wolvan's Homebr3w

### ISSUE THREAD

**Issue by NinjaBoyLao** [ksanislo/TitleDB#1]
Is there a way you could provide a user input field on the titleDB page, so that when a user links in a new repository for a project/tool/homebrew/app/whatever, they can also provide a brief summary of that app? that way, homebr3w could fetch it along with the other stuff it fetches. One of either you or wolvan would probably be the one to end up doing this as asking each and every app maker to fix the descriptions of their .cia files is a monumental task

**Comment by ksanislo** [comment]
While there's no good way to backport the functionality into the currently live version of titledb, this GitHub repo is the rewrite which has user/moderator accounts and editable records among a pile of other new features and improvements like the addition of 3dsx and a9lh bins to the listings.

Unfortunately, it will still be a while before this is ready for production deployment, as my free time for side projects has been fairly limited lately. Hopefully I'll be able to finish it up before the end of the year, but I can't make any promises on a delivery date.

**Comment by NinjaBoyLao** [comment]
sounds good, does that mean the rewrite will have this or a similar feature?

**Comment by ksanislo** [comment]
Yes, in the rewrite apps have an entry written up by a moderator account, and they can link to CIAs as well as 3dsx or bin files. The API side is mostly finished but without user file submitting working I can't put it up live yet.

**Comment by NinjaBoyLao** [comment]
thanks for the updates. Good luck!
