### ISSUE TITLE
Delete entry in TitleDB?

### ISSUE THREAD

**Issue by KunoichiZ** [ksanislo/TitleDB#11]
Hello. I'm the dev of Luma Updater and I had a question regarding the entries in TitleDB. I had to delete a recent release for Luma Updater (v2.2). However, I already submitted the update to TitleDB, so now it displays "https://github.com/KunoichiZ/lumaupdate/releases/download/v2.2/lumaupdater-2.2.zip", which doesn't exist.

Is it possible for someone to delete the entry for v2.2 for Luma Updater so that I can successfully upload the current version, v2.1.2? Or can someone change the entry to v2.1.2? I tried uploading the .zip and the .cia for v2.1.2, but the botched update v2.2 is all that shows up on TitleDB.

Any help is appreciated! Thank you! BTW, if you can change it, here is the proper link for v2.1.2: https://github.com/KunoichiZ/lumaupdate/releases/download/v2.1.2/lumaupdater-2.1.2.zip

**Comment by ksanislo** [comment]
@KunoichiZ I've set the v2.2 URL as disabled, so things are falling back to the older 2.1.2 again. I'll have to look into handling this sort of thing programmatically, as it really shouldn't need manual intervention to correct something like this. For the moment, if you need anything else changed just let me know.

**Comment by KunoichiZ** [comment]
Thank you so much for looking into this. Another question though, if and when I release v2.2, would I need to do anything to make it show up in TitleDB? Or do I just need to upload the link for it like always?

**Comment by ksanislo** [comment]
@KunoichiZ It _should_ be re-added by the GitHub scanner when it becomes a legit release again, but I can't think of any case where I've actually tested the behavior to verify that it works as intended. If it doesn't switch to the 2.2 URL within 30 minutes or so of being released, just open an issue or shoot me a message on reddit to get my attention and I'll figure out how to fix it then.

**Comment by KunoichiZ** [comment]
I'll re-open this issue if I run into an issue. Thank you for your help!
