### ISSUE TITLE
Copyrighted content uploaded to TitleDB

### ISSUE THREAD

**Issue by FrozenChen** [ksanislo/TitleDB#12]
The entry with titleid 0004000000E85100 (no name, no desccription) is a pokemon firered gba inject that doesnt even work properly. (because of how injection works) So it needs to be deleted.

**Comment by ksanislo** [comment]
@FrozenChen Thanks for pointing this out! I've removed the bad titleid you mentioned. Let me know if you spot any others that shouldn't be allowed in the list as well.
