### ISSUE TITLE
A lot copyrighted content uploaded to TitleDB

### ISSUE THREAD

**Issue by FrozenChen** [ksanislo/TitleDB#13]
Well this time they are actually working(some of them) and there is a lot of it, all of them injections.

- Crash Bandicoot(Gba injection) 
UniqueID CD0300
- Dragon Ball Z Super Sonic Warriors(Gba injection) 
UniqueID 45700
- Moemon Emerald(Pokemon emerald rom hack  injection) 
UniqueID 2DDE00
- Pokemon Diamond(Pokemon R/S/E romhack injection) 
UniqueID CC1700
- Pokemon Life(Pokemon R/S/E Romhack injection) 
UniqueID A08800
- Seiken Densetsu 3 (NES injection)
UniqueID C0BF00
- Terrfying 9/11 (idk about this one, couldnt install) 
UniqueID C0A700
- The Naked Little Mermaid ('_>' Lets just leave it at nes romhack, kill on sight) 
UniqueID 694C00

I may have missed other injects so be sure to check.

**Comment by ksanislo** [comment]
Thanks, I've cleared these all out.

**Comment by FrozenChen** [comment]
I missed this one, sorry
- DBZ Team Training(gba injection)
UniqueID: A38800

**Comment by ksanislo** [comment]
It''s gone too now. Thanks again!

**Comment by ghost** [comment]
Crash Bandicoot THA/XS GBA injection one was me, sorry ._.
