### ISSUE TITLE
Delete entries in TitleDB

### ISSUE THREAD

**Issue by BernardoGiordano** [ksanislo/TitleDB#14]
Hi, I would like to have some entries deleted since links for them are not working anymore and have been merged into other projects. Thank you

* MysteryGiftDump (000400000ECDB000)
* PKSV (000400000EC20000)
* Sharkive (000400000CC10100)
* TeamLIst Filler (000400000EC30000)

**Comment by ksanislo** [comment]
No trouble at all. The matching entries for these IDs have been delisted from the site. Let me know if you need anything else changed in the future.
