### ISSUE TITLE
[Suggestion] Implement @Steveice10's ticket title version reader

### ISSUE THREAD

**Issue by gaetschwartz** [ksanislo/TitleDB#15]
Hey ! @Steveice10 pushed a [pull request](https://github.com/ksanislo/TitleDB/pull/8) on this repo a while ago, but you did't give him any feedback, is it possible to take a look back at his PR ? It would  be pretty awesome from you x)

Best regards,
Blaxou

**Comment by ksanislo** [comment]
I'm not particularly interested in implementing "special" features for Steveice10, as honestly I think he's a bit of a jerk who has cloned my apps and ideas and given zero credit for them. Also, his PR against my app is pretty much untested crap and doesn't work for the majority of things which are indexed on the site.
