### ISSUE TITLE
[Feature request] A little bit more organization pls?

### ISSUE THREAD

**Issue by d0k3** [ksanislo/TitleDB#17]
I looked through the titledb just today, this is what I found:
* over 20(!) different versions of freeShop (two of them called "fefoSheep")
* about 8 different versions of JKSM
* 3 different versions of Themely (one with the name "3DSThemeManager")
* 3 different, completely indistuingishable versions of "Clock"

I guess I could continue this list endlessly. I do understand that having multiple entries for certain software / title IDs in the database can make sense (especially when a fork added controversial changes), but the way it is organized now is borderline unusable. No one knows which version to get.

So, a few suggestions:
* Cleanup the database, remove outdated and nonsense entries - this is a task that most likely has to be done by a human. Maybe crap entries to the database can be prevented in the future, keeping maintenance to a minimum. As superfluous titles can be recognized by their title IDs, cleaning this up shouldn't be too difficult.
* Group entries with identical title IDs, and emphasize the official build - the official build would be the most legit. The most legit source would be (f.e.) the original authors Github repo. Even with this, a cleanup makes sense (see above).

And, additional info - fefoSheep (one of the entries sharing the freeShop title ID) is not even a freeShop fork or offers similar functionalitiy. It shares the title ID deliberately to mislead users to download it (kudos to @fefoSheep here, masterful trolling is appreciated).

**Comment by ksanislo** [comment]
The way the data is organized and presented is a client issue, the backend is effectively just data only. Entries are grouped by "entry" via the API, and not titleid. How they're displayed can be cleaned up by a proper client if someone cares to write one.

Here's my half-ass client which shows how the data is actually stored much better than the old /v0  main interface or FBI/Homebr3w does, though it still has major problems and lacks a cohesive login method. https://3ds.titledb.com/static/admin/#/entry/list

The /v1 admin source is at https://github.com/ksanislo/TitleDB/tree/master/titledb/static/admin if you'd care to help get it to a usable state so we can have people regularly moderating the dataset.

**Comment by d0k3** [comment]
Okay, I see. This admin frontend won't make it easy to do a major cleanup. My JavaScript is beyound rusty, so I can´'t be of a lot help in improving the code. I'd offer my help where I can be of use, though. Are you missing moderators for the content?

I think it could be even enough (for now) to do a  major cleanup now (ugh, that won't be quick), and then just review the new entries at given intervals.

**Comment by GriffinG1** [comment]
@d0k3 as a note, fefosheep is a separate (meme) application that can be found [here](https://github.com/fefoSheep/fefoSheep-3DS)

**Comment by ksanislo** [comment]
@d0k3 If you'd like to moderate, I can set you up an account and try to hack the admin interface back into something that can at least authenticate and have write perms again. My free time is awfully short at the moment, so It might be a few more days before I can get to it. I'll let you know.

**Comment by 916253** [comment]
Sorry to necrobump, but as this is still an issue, I'd like to see some more done to organize and clean up, if you're willing to do what you said in the previous comment for me (or if @d0k3 is still up to the task?) i'd appreciate it

(
![image](https://user-images.githubusercontent.com/3783580/42417074-1fc72e9a-824d-11e8-9d1d-e71215bec671.png)so many duplicates >.>)

**Comment by d0k3** [comment]
Seconding that, @916253. My free time is short as it is right now, but I may be able to offer some help in getting this organized.
