### ISSUE TITLE
Web Interface uses "v0" api, causing it to return an outdated list.

### ISSUE THREAD

**Issue by Lustyn** [ksanislo/TitleDB#18]
Can it get a version bump/upgrade of some kind? Thanks!

**Comment by ksanislo** [comment]
I'm aware of the problem, but I really don't have the time to devote to further development of the project at this time. The web UI source is just javascript/ajax and available here in the project on GitHub if anyone else would care to take a stab at it though. There's also a preliminary /v1 based admin interface which is partially complete as well, source for both is available under https://github.com/ksanislo/TitleDB/tree/master/titledb/static
