### ISSUE TITLE
Submissions has been possibly broken since around last commit

### ISSUE THREAD

**Issue by FrozenChen** [ksanislo/TitleDB#19]
Looking around the API looking why the apps havent been updated, i noticed the submission page in the API(https://3ds.titledb.com/v1/submission , only possible cause i found, you might have a better idea)
If you check the date of the oldest stuck submission is around when the last changes were done. 
Since FBI ~~for whatever reason~~ now uses titledb to update it makes FBI unable to update since the version on titledb is always older than the one that updated with titledb.

**Comment by ksanislo** [comment]
Whoops, it seems that when I revamped the way I'm storing the database credentials, I didn't make them readable by the scheduled tasks that process updates. Fixed and re-scanning all known/submitted URLs now.
