### ISSUE TITLE
[Request] Add those Games to the TitleDB.

### ISSUE THREAD

**Issue by ghost** [ksanislo/TitleDB#21]
[Sega Master System Injects (Forward to Picodrive).zip](https://github.com/ksanislo/TitleDB/files/1996689/Sega.Master.System.Injects.Forward.to.Picodrive.zip)
[Super Nintendo Injects (Forward to Snes9x for 3ds).zip](https://github.com/ksanislo/TitleDB/files/1996690/Super.Nintendo.Injects.Forward.to.Snes9x.for.3ds.zip)
I Tested All those Games on my 3ds & they all Work.

**Comment by ksanislo** [comment]
Emulator injections are officially considered piracy as the emulator they're injected into is copyright to Nintendo, even when the ROM itself being used is public domain (which I don't suspect any of these are anyway.)

Basically, if there's an injected game on the site and it's brought to my attention, I'm obligated to remove them. I'm certainly not about to manually add a bunch of extra ones, as I'd get sued and the service itself would likely have to be shut down.
