### ISSUE TITLE
Users are uploading VC Titles/Injects

### ISSUE THREAD

**Issue by ghost** [ksanislo/TitleDB#23]
Dr. Robotnik's Plan B
FamiTale
Flappy Bird
Flappy Bird GBA
Kirby's Nightmare in Dreamland
NTRQ
Oracle of Hours
Robotnik's Revenge
Somari the Adventurer
Sonic Adventure
The Legend of Zelda:Parallel Worlds
Windows 98 for NES!
Zelda - Sacred Paradox

**Comment by ksanislo** [comment]
Thanks for pointing these out.
