### ISSUE TITLE
Roms in the DB

### ISSUE THREAD

**Issue by theredbaron1834** [ksanislo/TitleDB#24]
I don't know if you care, but I noticed someone added a few roms to the db, including:

Kirby Nightmare in Dreamland

Super Mario Advance 2 - Super Mario World

The Legend of Zelda - A Link to the Past & Four Swords

Tony Hawk Pro skater 2/4

The Urbz Sims In The City

Kirby Nightmare in Dreamland

Grand Theft Auto Advanced

I didn't see any others, but it was a pretty speed look, so I may have missed some.

**Comment by ksanislo** [comment]
@theredbaron1834 Thanks for pointing these out, I've cleared their titleID's from the database.
