### ISSUE TITLE
Commercial 3DS games listed

### ISSUE THREAD

**Issue by neoman4426** [ksanislo/TitleDB#26]
Possibly some others, but at a minimum Captain Toad US and Mario Kart 7 US have been added to the list by someone. In addition, the Mario Kart one leads to a broken link causing a description of "SMDH Decode Failed" and at least on HomeBr3w a series of dotted square glyphs as a title that cause it to freak out

**Comment by smileyhead** [comment]
I can't see Mario Kart 7 (just CTGP-7 and a save editor), but I can confirm Captain Toad being up there.

![image](https://user-images.githubusercontent.com/15932372/43529436-93b8b08c-95ab-11e8-94ad-092be07db83d.png)

**Comment by neoman4426** [comment]
The Mario Kart one I know of because the Title ID matches, it's not by name as the file itself is gone causing some errors. Title ID is 0004000000030800,

**Comment by BrightSideGames** [comment]
Can confirm both of these, and I just saw EarthBound on the database. Not sure if it's the official eShop release, but it shouldn't be on there either way.

**Comment by neoman4426** [comment]
Yeah, Earthbound one is an SNES9x based VC inject. Yeah, that shouldn't be there either. For completeness sake, 0004000009F33900 is the TITLEID that's under on the site, and unlike the others listed here still works.

**Comment by ksanislo** [comment]
Thanks, these have been cleaned out now.
