### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by connesc** [ksanislo/TitleDB#28]
Almost all routes seem to produce 500 errors ([example](https://api.titledb.com/v1/cia)).
Is there anything to do server-side in order to fix the problem?

Thanks!

**Comment by ksanislo** [comment]
As the index grows bigger, it seems that mysql is beginning to get into a fight with the OOM-killer that it just isn't going to win. I've got things up again for now, but I need to determine what can be done to lower memory usage, that or It just needs to move to a newer/bigger hosting environment.
