### ISSUE TITLE
TitleDB Broken?

### ISSUE THREAD

**Issue by QuickChemist** [ksanislo/TitleDB#29]
Website shows no database entries. According to reddit and gbatemp I am not the only one with this issue.
https://www.reddit.com/r/3dspiracy/comments/9keqhx/anyone_know_why_i_keep_getting_this_when_i_open/

**Comment by ksanislo** [comment]
Yeah, the site has outgrown the VM which has been hosting it for the last few years, and now the mysql instance is being killed off by the Out-of-Memory killer every so often. I'm looking for a reliable solution currently.
