### ISSUE TITLE
Quality control

### ISSUE THREAD

**Issue by 916253** [ksanislo/TitleDB#5]
It seems that there are several items listed here which contain copyrighted content or full game data, and they have been allowed to remain listed for quite some time without removal. 

![image](https://cloud.githubusercontent.com/assets/3783580/25469104/472beba0-2ae8-11e7-988f-b32b83aef739.png) - romhack of a flinstones game provided in full

![image](https://cloud.githubusercontent.com/assets/3783580/25469147/7aeaf166-2ae8-11e7-89a2-99a1973b97e8.png) - attempt at uploading a copy of terraria, a game which is available in the eshop for $19.99 (this seems to fail to install, however, but still--it shouldn't be here)

And i'm sure others which I missed.

**Comment by ksanislo** [comment]
I've cleaned up anything that looked like piracy or rom hacks, but I don't have time to check everything that is uploaded myself. Let me know if you find anything more that needs to be removed from the list.
